# Description: Workflow that updates markdown files by fetching them from other repositories. It runs every day at midnight automatically, or it can be triggered manually or by setting up a dispatch action in the lower level repo.
# Author: Cristian Jara-Figueroa, Phd Student MIT Media Lab
# Last updated: September 18, 2020
name: Update documentation from downstream repos

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [docs_update]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update CS_Brix
        run: bash .github/scripts/update.sh CityScope CS_Brix docsite/docs/backend master/docs/markdown/docusaurus.md 
      - name: Update CS_Proxymix
        run: bash .github/scripts/update.sh wiki/CityScope CS_Proxymix docsite/docs/backend Home.md
      # SYNTAX TO ADD REPOS
      # - name: Update REPO_NAME
        # run: bash .github/scripts/update.sh REPO_NAME_OWNER REPO_NAME DESTINATION_PATH(Defaults to docsite/docs/general) PATH_TO_FILE(Defaults to README.md)
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: crisjf
          author_email: crisjf@mit.edu
          message: "Commit from actions"
          add: "."
          ref: 'new_docsite'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
