# Description: Workflow that builds the website after a push to new_docsite branch
# Author: Cristian Jara-Figueroa, Phd Student MIT Media Lab
# Last updated: November 30, 2020
name: Build website using yarn

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - new_docsite

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    env:
      working-directory: ./docsite
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: new_docsite
      - name: List files and check location
        run: pwd && ls -l
        working-directory: ./docsite
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install yarn
        run: npm install -g yarn
        working-directory: ./docsite
      - name: yarn install and deploy
        run: yarn && yarn deploy
        working-directory: ./docsite
        env:
          GIT_USER: crisjf
      # - name: yarn install
      #   uses: borales/actions-yarn@v2.0.0
      #   with:
      #     cmd: install
      # - name: yarn deploy
      #   uses: borales/actions-yarn@v2.0.0
      #   env:
      #     GIT_USER: crisjf
      #   with:
      #     cmd: deploy


# Steps to deploy (bash)
# cd docsite
# yarn install
# export GIT_USER=crisjf
# yarn deploy