# Description: Workflow that builds the website after a push to new_docsite branch
# Author: Cristian Jara-Figueroa, Phd Student MIT Media Lab
# Last updated: November 30, 2020
name: Build website using yarn

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - new_docsite

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: new_docsite
      - name: yarn deploy
        uses: borales/actions-yarn@v2.0.0
        env:
          GIT_USER: crisjf
        # with:
          # cmd: deploy
      - name: List files
        run: ls -l && echo $GIT_USER

# Steps to deploy (bash)
# cd docsite
# yarn install
# export GIT_USER=crisjf
# yarn deploy